version: "3"

volumes:
  gem_cache:
  db_data:
  tmp_data:
  log_data:
  vendor:
  gem_dir:
  sockets:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    # restart: on-failure
    depends_on:
      - app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: sockets
        target: /app/tmp/sockets
        volume:
          nocopy: true
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes_from:
      - app
      
  app:
    platform: linux/x86_64
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "bundle install && bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
    ports:
      - "3000"
    volumes:
      - tmp_data:/app/tmp
      - log_data:/app/log
      - vendor:/app/vendor
      - gem_dir:/usr/local/bundle
      - gem_cache:/usr/local/bundle/gems
      - /var/tmp
      - type: bind
        source: .
        target: /app
      - type: volume
        source: sockets
        target: /app/tmp/sockets
        volume:
          nocopy: true